# Generated by Django 3.2.2 on 2021-05-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queuesystem', '0010_auto_20200429_1834'),
        ('queuesystem', '0010_auto_20200430_0100'),
    ]

    operations = [
    ]
